schemaVersion: provision.dev/v1alpha1
kind: Application
name: hello
components:
  web:
    role: http
    health:
      liveness:
        path: /live
      readiness:
        path: /ready
      candidateVerification:
        path: /verify
