schemaVersion: provision.dev/v1alpha1
kind: Environment
name: lab
application: provision-example-http
rollbackWindow: 30m0s
targets:
  base:
    kind: host
    address: base.local
    user: marlinf
implementations:
  web:
    kind: systemd
    target: base
    rollout: required
    endpoint:
      port: 18080
      drain:
        mode: bounded-http
        maxDuration: 2s
